engines:
  eslint:
    enabled: false
  duplication:
    enabled: false
checks:
  method-complexity:
    enabled: false
  method-lines:
    enabled: false
ratings:
  paths:
    - index.js
    - lib/**
